<h1>Sample Module</h1>
<?php 
if ($this->message) {
    echo "<h4>{$this->message}</h4>";
} 
?>
<div class="row">
    <div class="col-md-12">
        <h5>Has access to `test-sample-resource`: <?php echo var_export($this->getAccess('test-sample-resource'));?></h5>
        <?php 
        if (!$this->identity()) {
            $this->loginForm->prepare(); 
            echo $this->form()->openTag($this->loginForm->setAttribute('class', 'form-horizontal'));
            ?> 
              <div class="form-group">
                <label for="username" class="col-sm-2 control-label"><?php echo $this->loginForm->get('username')->getLabel();?></label>
                <div class="col-sm-10">
                    <?php echo $this->formElement($this->loginForm->get('username'));?>
                </div>
              </div>
              <div class="form-group">
                <label for="password" class="col-sm-2 control-label"><?php echo $this->loginForm->get('password')->getLabel();?></label>
                <div class="col-sm-10">
                    <?php echo $this->formElement($this->loginForm->get('password'));?>
                </div>
              </div> 
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <?php echo $this->formElement($this->loginForm->get('submit'));?> 
                </div>
              </div> 
            <?php 
            echo $this->form()->closeTag();
        } else { ?>
            <form action="" method="post">
                <input type="submit" value="Logout" class="btn btn-default" name="logout"/>
            </form>    
        <?php 
        }
        ?>
    </div>
</div>